example/rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :beavers

end

example/rails_app/app/models/beaver.rb
class Beaver < ActiveRecord::Base
end

example/rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

example/rails_app/app/controllers/beavers_controller.rb
class BeaversController < ApplicationController
  before_action :set_beaver, only: %i[show edit update destroy]

  # GET /beavers
  # GET /beavers.json
  def index
    @beavers = Beaver.all
  end

  # GET /beavers/1
  # GET /beavers/1.json
  def show; end

  # GET /beavers/new
  def new
    @beaver = Beaver.new
  end

  # GET /beavers/1/edit
  def edit; end

  # POST /beavers
  # POST /beavers.json
  def create
    @beaver = Beaver.new()

    respond_to do |format|
      if @beaver.save
        format.html { redirect_to @beaver, notice: 'Beaver was successfully created.' }
        format.json { render :show, status: :created, location: @beaver }
      else
        format.html { render :new }
        format.json { render json: @beaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beavers/1
  # PATCH/PUT /beavers/1.json
  def update
    respond_to do |format|
      if @beaver.update(beaver_params)
        format.html { redirect_to @beaver, notice: 'Beaver was successfully updated.' }
        format.json { render :show, status: :ok, location: @beaver }
      else
        format.html { render :edit }
        format.json { render json: @beaver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beavers/1
  # DELETE /beavers/1.json
  def destroy
    @beaver.destroy
    respond_to do |format|
      format.html { redirect_to beavers_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beaver
    @beaver = Beaver.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beaver_params
    params.require(:beaver).permit(:name)
  end
end

example/rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

example/rails_app/app/helpers/beavers_helper.rb
module BeaversHelper
end

example/rails_app/app/views/beavers/_form.html.erb
<%= form_for(@beaver) do |f| %>
  <% if @beaver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beaver.errors.count, "error") %> prohibited this beaver from being saved:</h2>

      <ul>
      <% @beaver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

example/rails_app/app/views/beavers/edit.html.erb
<h1>Editing beaver</h1>

<%= render 'form' %>

<%= link_to 'Show', @beaver %> |
<%= link_to 'Back', beavers_path %>

example/rails_app/app/views/beavers/index.html.erb
<h1>Listing beavers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beavers.each do |beaver| %>
      <tr>
        <td><%= beaver.name %></td>
        <td><%= link_to 'Show', beaver %></td>
        <td><%= link_to 'Edit', edit_beaver_path(beaver) %></td>
        <td><%= link_to 'Destroy', beaver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beaver', new_beaver_path %>

example/rails_app/app/views/beavers/new.html.erb
<h1>New beaver</h1>

<%= render 'form' %>

<%= link_to 'Back', beavers_path %>

example/rails_app/app/views/beavers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beaver.name %>
</p>

<%= link_to 'Edit', edit_beaver_path(@beaver) %> |
<%= link_to 'Back', beavers_path %>

example/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if features[:justin_beaver].enabled? %>
  <%= image_tag 'justin_beaver.jpg', width: 200, height: 200 %>
<% else %>
  <%= image_tag 'regular_beaver.jpg', width: 200, height: 200 %>
<% end %>
<%= yield %>

</body>
</html>